# Arquivo: .github/workflows/preview.yml

name: Preview Workflow
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Use a versão do Node.js adequada ao seu projeto

      - name: Build the static app
        run: |
          # Comando para construir o aplicativo estático
          # Por exemplo, se você estiver usando apenas arquivos HTML, CSS e JavaScript, este comando pode ser simplesmente:
          # npm install # ou yarn install
          # Ou pode não ser necessário nenhum comando, se você não estiver usando nenhum framework ou pré-processador.
          # Certifique-se de que a página index.html esteja presente na raiz do projeto.

      - name: Deploy to Azure Static Web Apps
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.adb9b41249e858d0eafc3475595722ca19c93009d9aa024e0a726fe2b771f40d3-49abdda0-dea5-4457-b7f5-f64e6e65d047010221393 }}
          # Substitua a variável acima pelo nome correto da sua secret contendo o token de API do Azure Static Web Apps
